all:
	$(MAKE) -C ansi-c 
	$(MAKE) -C colordebugger
	$(MAKE) -C graphics
	$(MAKE) -C libsploit

clean:
	$(MAKE) -C ansi-c clean
	$(MAKE) -C colordebugger clean
	$(MAKE) -C graphics clean
	$(MAKE) -C libsploit clean


